name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run REST controller tests
      run: npm run test-controller-rest
    
    - name: Start REST server and run it in background
      run: npm run start-rest &
    
    - name: Start GraphQL server and run it in background
      run: npm run start-graphql &

    - name: Wait until the server is ready
      run: sleep 5

    - name: Run REST HTTP tests
      run: npm run test-external-rest
    
    - name: Run GraphQL HTTP tests
      run: npm run test-external-graphql
